project:
  type: book

book:
  title: "TPU LLM Inference Handbook"
  author: "Gang Chen"
  date: "7/18/2025"
  chapters:
    - index.qmd
    - 02-llama-jetstream-inference.qmd
    - 03-scaling-gke-jetstream.qmd
    - 04-vllm-inference.qmd
    - 05-production-and-cost.qmd
    - references.qmd
        

bibliography: references.bib

format:
  html:
    css: styles.css
    code-fold: true
    page-layout: full
    theme:
      - darkly
      - brand
    number-sections: false
    toc: true
    toc-location: left
  pdf:
    documentclass: scrreprt
