project:
  type: book

book:
  title: "TPU LLM Inference Handbook"
  author: "Gang Chen"
  date: "7/18/2025"
  chapters:
    - index.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    css: styles.css
    code-fold: true
    page-layout: full
    theme:
      - darkly
      - brand
    number-sections: false
    toc: true
    toc-location: left
  pdf:
    documentclass: scrreprt
